### ISSUE TITLE
y_true & y_pred

### ISSUE THREAD

**Issue by helloworldto** [unmix-io/unmix-net#1]
Hi, I'm interested in your project. However, I wonder where you defined the parameters y_true & y_pred. Could you tell me? My address is zhanghui7...@stu.ouc.edu.cn.

**Comment by kaufmann-a** [comment]
The project is in a very early stage and was set up a short while ago. Parameters will be defined in a later iteration.

**Comment by helloworldto** [comment]
Thank you for your reply.

**Comment by davidflury** [comment]
Hi
The split of training and validation files happens in our [dataloder.py]( https://github.com/unmix-io/unmix-net/blob/master/unmix/source/data/dataloader.py).
Data is served by a training and validation [DataGeneratory](https://github.com/unmix-io/unmix-net/blob/master/unmix/source/data/datagenerator.py).
Keras passes the y_true and y_pred to the metrics by itself.
